<div class="fotos">
Aqui vão as imagens
<p>..</p>
<p>..</p>
<p>..</p>
<p>..</p>
<p>..</p>
<p>..</p>
<p>..</p>
<p>..</p>
<p>..</p>
</div>
<h1>Brasil Sistemas</h1>
	<h2>Software Finanças BR</h2>
	<p>O sistema finanças BR é a solução completa de controle financeiro para sua empresa, o sistema tem desde operações básicas de cadastro de contas, a um controle infeligente de cheques, banco e plano de contas, oferecendo relatório detalhados de todas as movimentaçãoes financeiras de sua empresa</p>

	<h2>Tecnoligia</h2>
	<p>O sistema é distribuido em plataforma de nuvem, seguindo as tendências mundiais de desenvolvimento de distribuição de software</p>
	<p>O Software oferecido como serviço tem todas as vantagens da mobilidade e acessibilidade que a internet proporciona, para quem uma dispositivos moveis como Smartphomes ou Tablets pode acessá-lo e opera-lo diretamente de seu dispositivo sem precisar instalar nada.