<?php echo $this->doctype(); ?>
<html lang="pt-br" xmlns="http://www.w3.org/1999/xhtml">

<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink() ->prependStylesheet($this->baseUrl('/styles/main.css')); ?>
	<?php echo $this->headScript()	->appendFile($this->baseUrl(). '/js/jquery-1.6.min.js') ?>
	<script type="text/javascript">
		$(document).ready(function() {
  /* for keeping track of what's "open" */
  var activeClass = 'dropdown-active', showingDropdown, showingMenu, showingParent;
  /* hides the current menu */
  var hideMenu = function() {
    if(showingDropdown) {
      showingDropdown.removeClass(activeClass);
      showingMenu.hide();
    }
  };
  
  /* recurse through dropdown menus */
  $('.dropdown').each(function() {
    /* track elements: menu, parent */
    var dropdown = $(this);
    var menu = dropdown.next('div.dropdown-menu'), parent = dropdown.parent();
    /* function that shows THIS menu */
    var showMenu = function() {
      hideMenu();
      showingDropdown = dropdown.addClass('dropdown-active');
      showingMenu = menu.show();
      showingParent = parent;
    };
    /* function to show menu when clicked */
    dropdown.bind('click',function(e) {
      if(e) e.stopPropagation();
      if(e) e.preventDefault();
      showMenu();
    });
    /* function to show menu when someone tabs to the box */
    dropdown.bind('focus',function() {
      showMenu();
    });
  });
  
  /* hide when clicked outside */
  $(document.body).bind('click',function(e) {
    if(showingParent) {
      var parentElement = showingParent[0];
      if(!$.contains(parentElement,e.target) || !parentElement == e.target) {
        hideMenu();
      }
    }
  });
});
	</script>
</head>
    
<body>
	<div id="topo">
		<div class="centro-topo"><h1 class="t-empresa">Brasil Sistemas e Tecnologia</h1>
		<div class="menu">
		<div id="menu"><div class="relative">
		<a href="/demos" title="Cadastros" id="dd2" class="dropdown" style="width:170px;text-decoration:none;"><span>Cadastros</span></a>
  			<div id="dropdown2" class="dropdown-menu">
  				<ul>
	    			<li><a href="#" title="Cadastro de Usuários">Usuários</a></li>
	    			<li><a href="#" title="Cadastro de Entidades">Entidades</a></li>
	    			<li><a href="#" title="Cadastro de Caixas">Caixas</a></li>
	    			<li><a href="#" title="Cadastro de Contas correntes">Contas correntes</a></li>
	    			<li><a href="#" title="Cadastro de Bancos">Bancos</a></li>
	    			<li><a href="#" title="Cadastro de Tipos de documentos">Tipos de documentos</a></li>
	    			<li><a href="#" title="Cadastro de Portadores">Portadores</a></li>
    			</ul>
  			</div>
		</div></div>

		<div id="menu"><div class="relative">
  		<a href="/demos" title="Lançamentos" id="dd2" class="dropdown"  style="width:170px;text-decoration:none;"><span>Lançamentos</span></a>
 			<div id="dropdown2" class="dropdown-menu">
 				<ul>
		          <li><a href="#" title="Lançamento Movimentação caixa">Caixa</a></li>
		          <li><a href="#" title="Lançamento Movimentação conta corrente">Conta corrente</a></li>
		          <li><a href="#" title="Lançamento Contas a receber">Contas a receber</a></li>
		          <li><a href="#" title="Lançamento Contas a pagar">Contas a pagar</a></li>
		          <li><a href="#" title="Lançamento Tele cobrança">Tele cobrança</a></li>
		          <li><a href="#" title="Lançamento Cheques recebidos">Cheques recebidos</a></li>
		        </ul>
    		</div>
		</div></div>
		
		<div id="menu"><div class="relative">
  		<a href="/demos" title="Lançamentos" id="dd2" class="dropdown" style="width:170px;text-decoration:none;"><span>Relatórios</span></a>
 			<div id="dropdown2" class="dropdown-menu">
 				<ul>
          			<li><a href="#" title="Relatório de Contas a pagar">Contas a pagar</a></li>
          			<li><a href="#" title="Relatório de Contas a receber">Contas a receber</a></li>
          			<li><a href="#" title="Relatório de Movimentação caixa">Movimentação caixa</a></li>
          			<li><a href="#" title="Relatório de Movimentação conta corrente">Movimentação conta corrente</a></li>
          			<li><a href="#" title="Relatório de Pagamentos">Pagamentos</a></li>
          			<li><a href="#" title="Relatório de Recebimentos">Recebimentos</a></li>
          			<li><a href="#" title="Relatório de Cheques recebidos">Cheques recebidos</a></li>
          			<li><a href="#" title="Relatório de Plano de contas">Plano de contas</a></li>
          			<li><a href="#" title="Relatório de Previsão de caixa">Previsão de caixa</a></li>
          			<li><a href="#" title="Relatório de Gráficos">Gráficos</a></li>
          			<li><a href="#" title="Relatório de Entidades">Entidades</a></li>
          			<li><a href="#" title="Relatório de DRE">DRE</a></li>
 				</ul>
    		</div>
		</div></div>
		
		<div id="menu"><div class="relative">
  		<a href="/demos" title="Lançamentos" id="dd2" class="dropdown" style="width:170px;text-decoration:none;"><span>Configurações</span></a>
 			<div id="dropdown2" class="dropdown-menu">
 				<ul>
 					<li><a href="#" title="Configurações de Usuários">Usuários</a></li>
 				    <li><a href="#" title="Configurações de Empresas">Empresas</a></li>
    				<li><a href="#" title="Configurações de Parâmetros">Parâmetros</a></li>
    				<li><a href="#" title="Configurações de Tabelas">Tabelas</a></li>
    				<li><a href="#" title="Configurações de Entidades">Entidades</a></li>
    				<li><a href="#" title="Configurações ">Configurações</a></li>
    			</ul>
    		</div>
		</div></div>
		
	</div>
	</div>
	</div>
    <div id="conteiner"><?php echo $this->layout()->content; ?></div>
</body>
</html>