<div class="resumo">
  <h2>Resumo das operações</h2>
  <div class="resumoc1">
    <h3>Contas a pagar</h3>
	<ul>
		<li>Hoje (5)</li>
		<li>Esta semana (15)</li>
		<li>Este mês (25)</li>
		<li><strong>Todos</strong></li>
	</ul>	
	
	<h3>Contas a receber</h3>
	<ul>
		<li>Hoje (30)</li>
		<li>Esta semana (50)</li>
		<li>Este mês (100)</li>
		<li><strong>Todos</strong></li>
	</ul>	
	
  </div>

	<div class="resumoc2">
		<h3>Compromissos</h3>
		<ul>
			<li>Lavar a Louça</li>
			<li>Cotação da impressora</li>
			<li>Comprar ingresso do pagode</li>
			<li><strong>Todos</strong></li>
		</ul>
	
	  <h3>Total de Cheques</h3>
	  	<ul>
			<li>Lavar a Louça</li>
			<li>Cotação da impressora</li>
			<li>Comprar ingresso do pagode</li>
			<li><strong>Todos</strong></li>
		</ul>
</div>	

</div>
<div class="wid">
<h3>Saldo</h3>
  <p>Despesas:xxxx</p>
  <p>Receitas:ccc</p>
  
  <h3>Ultimo acesso</h3>
  <p>Data:xxxx</p>
  <p>Hora:ccc</p>
 
  <h3>Ultimo lançamentos</h3>
  <p>Moniventação:xxxx</p>
  <p>Cadastro:ccc</p>
</div>
<div class="clear"></div>